name: sample_capture_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 核心功能套件
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^4.1.7
  image_picker: ^1.1.2
  http: ^1.2.1
  uuid: ^4.4.0
  shared_preferences: ^2.2.3

  # 安全性與驗證核心
  passkeys: ^2.0.0
  # google_play_integrity: ^0.1.1 # //存在錯誤
  app_device_integrity: ^1.1.0
  logging: ^1.3.0

  # 狀態管理
  flutter_riverpod: ^2.5.1

  # 其他輔助工具
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true