name: sample_capture_app
description: A high-trust data capture proof-of-concept application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# 【修正】鎖定一組已知的穩定版本以解決依賴衝突
dependencies:
  flutter:
    sdk: flutter

  # Passkeys / WebAuthn 核心套件
  passkeys: ^2.9.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Camera
  camera: ^0.11.0+1

  # Location Services
  geolocator: ^11.0.0 # 使用一個更穩定的版本

  # Permissions
  permission_handler: ^11.3.1

  # Device & App Integrity
  app_device_integrity: ^1.1.0

  # Image Processing (for pHash)
  image: ^4.1.7

  # Networking
  http: ^1.2.0

  # Logging
  logging: ^1.2.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

